### ISSUE TITLE
Arrow in case statement error

### ISSUE THREAD

**Issue by Qoyyuum** [Shashank18May/Calculator#1]
Hi @Shashank18May 

You need to specify what Java version is required to run this. I followed your README to compile it and it gives me this:

```powershell
> javac Caluclator.java
Caluclator.java:153: error: : expected
                                case '+' -> num3 = num1 + num2;
                                        ^
Caluclator.java:153: error: illegal start of expression        
                                case '+' -> num3 = num1 + num2;
                                         ^
Caluclator.java:154: error: : expected
                                case '-' -> num3 = num1 - num2;
                                        ^
Caluclator.java:154: error: illegal start of expression        
                                case '-' -> num3 = num1 - num2;
                                         ^
Caluclator.java:155: error: : expected
                                case '*' -> num3 = num1 * num3;
                                        ^
Caluclator.java:155: error: illegal start of expression        
                                case '*' -> num3 = num1 * num3;
                                         ^
Caluclator.java:156: error: : expected
                                case '/' -> num3 = num1 / num2;
                                        ^
Caluclator.java:156: error: illegal start of expression
                                case '/' -> num3 = num1 / num2;
                                         ^
8 errors
```

Checking on those lines, my IDE says that this type of arrow in case statement is only supported from Java 14 onwards but you claim that it works on Java 1.7.5 and above. I'm using Java 1.8.0 and this doesn't work for me.

**Comment by Shashank18May** [comment]
This was an enhanced form of switch case insisted by my IDK.
Changed it back to normal switch case so that it does not create any issue

**Comment by Qoyyuum** [comment]
That fixed it but you should put your changes into a Pull Request and directly commit to main branch to show which commits fixes which issue. You can close this issue as I don't see a problem with it now.
